// Static fund lookup table for IG Wealth Management iProfile funds.
// Checked before any web search runs — add new funds here to avoid API calls.
// To add a fund: copy an existing entry, change the code and values, save and redeploy.
// Last updated: 2026-03-28 | Source: ig.ca

const FUND_LIBRARY = {
  IGI1889: {
    code: 'IGI1889',
    fullName: 'iProfile Low Volatility Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Global Equity',
    mer: 0.63,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'US equity', percent: 52.54 },
      { name: 'International equity', percent: 42.29 },
      { name: 'Canadian equity', percent: 3.99 },
      { name: 'Cash & equivalents', percent: 1.25 },
      { name: 'Other', percent: -0.07 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 52.55 },
      { name: 'Japan', percent: 9.18 },
      { name: 'Europe', percent: 18.87 },
      { name: 'Asia ex-Japan', percent: 4.11 },
      { name: 'Canada', percent: 4.07 },
      { name: 'Other/EM', percent: 11.22 },
    ],
    benchmarkIndex: 'MSCI World Index',
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI1883: {
    code: 'IGI1883',
    fullName: 'iProfile Active Allocation Private Pool II Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Tactical Balanced',
    mer: 0.70,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'International equity', percent: 34.17 },
      { name: 'Cash & equivalents', percent: 18.93 },
      { name: 'Canadian equity', percent: 14.43 },
      { name: 'US equity', percent: 11.44 },
      { name: 'Fixed income', percent: 10.66 },
      { name: 'Other', percent: 10.37 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 39.55 },
      { name: 'Canada', percent: 15.71 },
      { name: 'Japan', percent: 11.50 },
      { name: 'Europe', percent: 17.71 },
      { name: 'Asia ex-Japan', percent: 1.81 },
      { name: 'Other/EM', percent: 13.72 },
    ],
    benchmarkIndex: null,
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI1891: {
    code: 'IGI1891',
    fullName: 'iProfile ETF Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Global Equity',
    mer: 0.12,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'US equity', percent: 58.75 },
      { name: 'International equity', percent: 33.61 },
      { name: 'Canadian equity', percent: 4.83 },
      { name: 'Cash & equivalents', percent: 0.11 },
      { name: 'Other', percent: 2.70 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 58.85 },
      { name: 'Japan', percent: 7.88 },
      { name: 'Canada', percent: 4.84 },
      { name: 'Europe', percent: 15.17 },
      { name: 'Asia ex-Japan', percent: 2.28 },
      { name: 'Other/EM', percent: 10.98 },
    ],
    benchmarkIndex: 'MSCI World Index',
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI153: {
    code: 'IGI153',
    fullName: 'iProfile U.S. Equity Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'US Equity',
    mer: 0.71,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'US equity', percent: 88.74 },
      { name: 'International equity', percent: 5.08 },
      { name: 'Cash & equivalents', percent: 1.77 },
      { name: 'Canadian equity', percent: 0.27 },
      { name: 'Other', percent: 4.14 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 88.99 },
      { name: 'Europe', percent: 4.38 },
      { name: 'Canada', percent: 0.42 },
      { name: 'Asia ex-Japan', percent: 0.39 },
      { name: 'Japan', percent: 0.0 },
      { name: 'Other/EM', percent: 5.82 },
    ],
    benchmarkIndex: 'S&P 500 Index',
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI152: {
    code: 'IGI152',
    fullName: 'iProfile Canadian Equity Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Canadian Equity',
    mer: 0.65,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'Canadian equity', percent: 89.83 },
      { name: 'US equity', percent: 5.86 },
      { name: 'International equity', percent: 1.01 },
      { name: 'Cash & equivalents', percent: 0.42 },
      { name: 'Other', percent: 2.88 },
    ],
    geographicAllocation: [
      { name: 'Canada', percent: 90.41 },
      { name: 'United States', percent: 5.88 },
      { name: 'Europe', percent: 0.81 },
      { name: 'Japan', percent: 0.0 },
      { name: 'Asia ex-Japan', percent: 0.09 },
      { name: 'Other/EM', percent: 2.81 },
    ],
    benchmarkIndex: 'S&P/TSX Composite Index',
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI154: {
    code: 'IGI154',
    fullName: 'iProfile International Equity Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'International Equity',
    mer: 0.62,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'International equity', percent: 96.52 },
      { name: 'Cash & equivalents', percent: 1.37 },
      { name: 'Canadian equity', percent: 0.56 },
      { name: 'Other', percent: 1.55 },
    ],
    geographicAllocation: [
      { name: 'Japan', percent: 22.80 },
      { name: 'Europe', percent: 53.64 },
      { name: 'Asia ex-Japan', percent: 4.45 },
      { name: 'Other/EM', percent: 19.11 },
    ],
    benchmarkIndex: 'MSCI EAFE Index',
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI156: {
    code: 'IGI156',
    fullName: 'iProfile Fixed Income Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Global Core Plus Fixed Income',
    mer: 0.18,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'Fixed income', percent: 84.62 },
      { name: 'Cash & equivalents', percent: 9.43 },
      { name: 'Other', percent: 5.95 },
    ],
    geographicAllocation: [
      { name: 'Canada', percent: 50.99 },
      { name: 'United States', percent: 22.27 },
      { name: 'Japan', percent: 3.27 },
      { name: 'Europe', percent: 5.27 },
      { name: 'Other/EM', percent: 18.20 },
    ],
    benchmarkIndex: 'FTSE Canada Universe Bond Index',
    riskRating: 'Low to Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI155: {
    code: 'IGI155',
    fullName: 'iProfile Emerging Markets Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Emerging Markets Equity',
    mer: 0.63,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'International equity', percent: 97.91 },
      { name: 'Cash & equivalents', percent: 1.72 },
      { name: 'US equity', percent: 0.61 },
      { name: 'Other', percent: -0.24 },
    ],
    geographicAllocation: [
      { name: 'Asia ex-Japan', percent: 55.59 },
      { name: 'Other/EM', percent: 32.03 },
      { name: 'Japan', percent: 0.0 },
      { name: 'United States', percent: 0.0 },
      { name: 'Canada', percent: 0.0 },
      { name: 'Europe', percent: 12.38 },
    ],
    benchmarkIndex: 'MSCI Emerging Markets Index',
    riskRating: 'Medium to High',
    dataAsAt: '2026-01-31',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI1886: {
    code: 'IGI1886',
    fullName: 'iProfile Active Allocation Private Pool III Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Tactical Balanced',
    mer: 0.76,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'International equity', percent: 38.47 },
      { name: 'Canadian equity', percent: 16.52 },
      { name: 'Cash & equivalents', percent: 15.97 },
      { name: 'US equity', percent: 13.50 },
      { name: 'Fixed income', percent: 3.78 },
      { name: 'Other', percent: 11.76 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 38.50 },
      { name: 'Canada', percent: 17.37 },
      { name: 'Japan', percent: 12.13 },
      { name: 'Europe', percent: 17.94 },
      { name: 'Other/EM', percent: 14.06 },
    ],
    benchmarkIndex: null,
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI1880: {
    code: 'IGI1880',
    fullName: 'iProfile Active Allocation Private Pool I Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Tactical Balanced',
    mer: 0.69,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'International equity', percent: 29.18 },
      { name: 'Cash & equivalents', percent: 17.91 },
      { name: 'Fixed income', percent: 21.05 },
      { name: 'Canadian equity', percent: 12.41 },
      { name: 'US equity', percent: 9.52 },
      { name: 'Other', percent: 9.93 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 37.09 },
      { name: 'Canada', percent: 14.04 },
      { name: 'Japan', percent: 11.45 },
      { name: 'Europe', percent: 17.44 },
      { name: 'Asia ex-Japan', percent: 3.51 },
      { name: 'Other/EM', percent: 16.47 },
    ],
    benchmarkIndex: null,
    riskRating: 'Low to Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI1927: {
    code: 'IGI1927',
    fullName: 'iProfile Active Allocation Private Pool IV Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Global Equity',
    mer: 0.92,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'International equity', percent: 45.72 },
      { name: 'Canadian equity', percent: 19.53 },
      { name: 'US equity', percent: 18.64 },
      { name: 'Cash & equivalents', percent: 0.45 },
      { name: 'Other', percent: 15.66 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 27.81 },
      { name: 'Canada', percent: 19.77 },
      { name: 'Japan', percent: 14.61 },
      { name: 'Europe', percent: 23.12 },
      { name: 'Other/EM', percent: 14.69 },
    ],
    benchmarkIndex: null,
    riskRating: 'Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
  IGI1893: {
    code: 'IGI1893',
    fullName: 'iProfile Alternatives Private Pool Series I',
    fundCompany: 'IG Wealth Management',
    cifscCategory: 'Alternative Multi-Strategy',
    mer: 0.84,
    distributionYield: 0.0,
    distributionFrequency: null,
    assetAllocation: [
      { name: 'Cash & equivalents', percent: 48.21 },
      { name: 'US equity', percent: 31.67 },
      { name: 'International equity', percent: 14.43 },
      { name: 'Fixed income', percent: 3.44 },
      { name: 'Canadian equity', percent: 0.52 },
      { name: 'Other', percent: 1.73 },
    ],
    geographicAllocation: [
      { name: 'United States', percent: 38.20 },
      { name: 'Canada', percent: 17.07 },
      { name: 'Japan', percent: 6.76 },
      { name: 'Europe', percent: 5.94 },
      { name: 'Other/EM', percent: 32.03 },
    ],
    benchmarkIndex: null,
    riskRating: 'Low to Medium',
    dataAsAt: '2026-02-28',
    source: 'ig.ca',
    verified: true,
    confidence: 'High',
  },
};

export default FUND_LIBRARY;
